
// This file has been generated by the GUI designer. Do not modify.
namespace osrepodbmgr
{
	public partial class dlgSettings
	{
		private global::Gtk.HBox hbox2;

		private global::Gtk.VBox vbox3;

		private global::Gtk.HBox hbox26;

		private global::Gtk.Label lblDatabase;

		private global::Gtk.Entry txtDatabase;

		private global::Gtk.Button btnDatabase;

		private global::Gtk.HBox hbox25;

		private global::Gtk.Label lblRepository;

		private global::Gtk.Entry txtRepository;

		private global::Gtk.Button btnRepository;

		private global::Gtk.HBox hbox24;

		private global::Gtk.Label lblTmp;

		private global::Gtk.Entry txtTmp;

		private global::Gtk.Button btnTmp;

		private global::Gtk.HBox hbox23;

		private global::Gtk.Label lblUnar;

		private global::Gtk.Entry txtUnar;

		private global::Gtk.Button btnUnar;

		private global::Gtk.Label lblUnarVersion;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label lblCompAlg;

		private global::Gtk.ComboBox cmbCompAlg;

		private global::Gtk.VBox vbox4;

		private global::Gtk.CheckButton chkAntivirus;

		private global::Gtk.Frame frmClamd;

		private global::Gtk.Alignment GtkAlignment6;

		private global::Gtk.VBox vbox6;

		private global::Gtk.CheckButton chkClamd;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label lblClamdHost;

		private global::Gtk.Entry txtClamdHost;

		private global::Gtk.Label lblClamdPort;

		private global::Gtk.SpinButton spClamdPort;

		private global::Gtk.Button btnClamdTest;

		private global::Gtk.Label lblClamdVersion;

		private global::Gtk.CheckButton chkClamdIsLocal;

		private global::Gtk.Label GtkLabel8;

		private global::Gtk.Frame frmVirusTotal;

		private global::Gtk.Alignment GtkAlignment7;

		private global::Gtk.VBox vbox7;

		private global::Gtk.CheckButton chkVirusTotal;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Label label6;

		private global::Gtk.Entry txtVirusTotal;

		private global::Gtk.Button btnVirusTotal;

		private global::Gtk.Label lblVirusTotal;

		private global::Gtk.Label GtkLabel12;

		private global::Gtk.HBox hbox18;

		private global::Gtk.Button btnCancel;

		private global::Gtk.Button btnApply;

		private global::Gtk.Button btnDialog;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget osrepodbmgr.dlgSettings
			this.Name = "osrepodbmgr.dlgSettings";
			this.Title = global::Mono.Unix.Catalog.GetString("Settings");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child osrepodbmgr.dlgSettings.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "vbox5";
			w1.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox26 = new global::Gtk.HBox();
			this.hbox26.Name = "hbox26";
			this.hbox26.Spacing = 6;
			// Container child hbox26.Gtk.Box+BoxChild
			this.lblDatabase = new global::Gtk.Label();
			this.lblDatabase.Name = "lblDatabase";
			this.lblDatabase.LabelProp = global::Mono.Unix.Catalog.GetString("Database file");
			this.hbox26.Add(this.lblDatabase);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.lblDatabase]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox26.Gtk.Box+BoxChild
			this.txtDatabase = new global::Gtk.Entry();
			this.txtDatabase.CanFocus = true;
			this.txtDatabase.Name = "txtDatabase";
			this.txtDatabase.IsEditable = true;
			this.txtDatabase.InvisibleChar = '●';
			this.hbox26.Add(this.txtDatabase);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.txtDatabase]));
			w3.Position = 1;
			// Container child hbox26.Gtk.Box+BoxChild
			this.btnDatabase = new global::Gtk.Button();
			this.btnDatabase.CanFocus = true;
			this.btnDatabase.Name = "btnDatabase";
			this.btnDatabase.UseUnderline = true;
			this.btnDatabase.Label = global::Mono.Unix.Catalog.GetString("Choose");
			global::Gtk.Image w4 = new global::Gtk.Image();
			w4.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-open", global::Gtk.IconSize.Menu);
			this.btnDatabase.Image = w4;
			this.hbox26.Add(this.btnDatabase);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.btnDatabase]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox3.Add(this.hbox26);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox26]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox25 = new global::Gtk.HBox();
			this.hbox25.Name = "hbox25";
			this.hbox25.Spacing = 6;
			// Container child hbox25.Gtk.Box+BoxChild
			this.lblRepository = new global::Gtk.Label();
			this.lblRepository.Name = "lblRepository";
			this.lblRepository.LabelProp = global::Mono.Unix.Catalog.GetString("Repository folder");
			this.hbox25.Add(this.lblRepository);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.lblRepository]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox25.Gtk.Box+BoxChild
			this.txtRepository = new global::Gtk.Entry();
			this.txtRepository.CanFocus = true;
			this.txtRepository.Name = "txtRepository";
			this.txtRepository.IsEditable = true;
			this.txtRepository.InvisibleChar = '●';
			this.hbox25.Add(this.txtRepository);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.txtRepository]));
			w8.Position = 1;
			// Container child hbox25.Gtk.Box+BoxChild
			this.btnRepository = new global::Gtk.Button();
			this.btnRepository.CanFocus = true;
			this.btnRepository.Name = "btnRepository";
			this.btnRepository.UseUnderline = true;
			this.btnRepository.Label = global::Mono.Unix.Catalog.GetString("Choose");
			global::Gtk.Image w9 = new global::Gtk.Image();
			w9.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-open", global::Gtk.IconSize.Menu);
			this.btnRepository.Image = w9;
			this.hbox25.Add(this.btnRepository);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.btnRepository]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox3.Add(this.hbox25);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox25]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox24 = new global::Gtk.HBox();
			this.hbox24.Name = "hbox24";
			this.hbox24.Spacing = 6;
			// Container child hbox24.Gtk.Box+BoxChild
			this.lblTmp = new global::Gtk.Label();
			this.lblTmp.Name = "lblTmp";
			this.lblTmp.LabelProp = global::Mono.Unix.Catalog.GetString("Temporary folder");
			this.hbox24.Add(this.lblTmp);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.lblTmp]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox24.Gtk.Box+BoxChild
			this.txtTmp = new global::Gtk.Entry();
			this.txtTmp.CanFocus = true;
			this.txtTmp.Name = "txtTmp";
			this.txtTmp.IsEditable = true;
			this.txtTmp.InvisibleChar = '●';
			this.hbox24.Add(this.txtTmp);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.txtTmp]));
			w13.Position = 1;
			// Container child hbox24.Gtk.Box+BoxChild
			this.btnTmp = new global::Gtk.Button();
			this.btnTmp.CanFocus = true;
			this.btnTmp.Name = "btnTmp";
			this.btnTmp.UseUnderline = true;
			this.btnTmp.Label = global::Mono.Unix.Catalog.GetString("Choose");
			global::Gtk.Image w14 = new global::Gtk.Image();
			w14.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-open", global::Gtk.IconSize.Menu);
			this.btnTmp.Image = w14;
			this.hbox24.Add(this.btnTmp);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.btnTmp]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			this.vbox3.Add(this.hbox24);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox24]));
			w16.Position = 2;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox23 = new global::Gtk.HBox();
			this.hbox23.Name = "hbox23";
			this.hbox23.Spacing = 6;
			// Container child hbox23.Gtk.Box+BoxChild
			this.lblUnar = new global::Gtk.Label();
			this.lblUnar.Name = "lblUnar";
			this.lblUnar.LabelProp = global::Mono.Unix.Catalog.GetString("Path to unar");
			this.hbox23.Add(this.lblUnar);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.lblUnar]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox23.Gtk.Box+BoxChild
			this.txtUnar = new global::Gtk.Entry();
			this.txtUnar.CanFocus = true;
			this.txtUnar.Name = "txtUnar";
			this.txtUnar.IsEditable = true;
			this.txtUnar.InvisibleChar = '●';
			this.hbox23.Add(this.txtUnar);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.txtUnar]));
			w18.Position = 1;
			// Container child hbox23.Gtk.Box+BoxChild
			this.btnUnar = new global::Gtk.Button();
			this.btnUnar.CanFocus = true;
			this.btnUnar.Name = "btnUnar";
			this.btnUnar.UseUnderline = true;
			this.btnUnar.Label = global::Mono.Unix.Catalog.GetString("Choose");
			global::Gtk.Image w19 = new global::Gtk.Image();
			w19.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-open", global::Gtk.IconSize.Menu);
			this.btnUnar.Image = w19;
			this.hbox23.Add(this.btnUnar);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.btnUnar]));
			w20.Position = 2;
			w20.Expand = false;
			w20.Fill = false;
			this.vbox3.Add(this.hbox23);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox23]));
			w21.Position = 3;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.lblUnarVersion = new global::Gtk.Label();
			this.lblUnarVersion.Name = "lblUnarVersion";
			this.lblUnarVersion.LabelProp = global::Mono.Unix.Catalog.GetString("label1");
			this.vbox3.Add(this.lblUnarVersion);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.lblUnarVersion]));
			w22.Position = 4;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.lblCompAlg = new global::Gtk.Label();
			this.lblCompAlg.Name = "lblCompAlg";
			this.lblCompAlg.LabelProp = global::Mono.Unix.Catalog.GetString("Compression algorithm");
			this.hbox1.Add(this.lblCompAlg);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.lblCompAlg]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.cmbCompAlg = global::Gtk.ComboBox.NewText();
			this.cmbCompAlg.Name = "cmbCompAlg";
			this.hbox1.Add(this.cmbCompAlg);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.cmbCompAlg]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			this.vbox3.Add(this.hbox1);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox1]));
			w25.Position = 5;
			w25.Expand = false;
			w25.Fill = false;
			this.hbox2.Add(this.vbox3);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox3]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.chkAntivirus = new global::Gtk.CheckButton();
			this.chkAntivirus.CanFocus = true;
			this.chkAntivirus.Name = "chkAntivirus";
			this.chkAntivirus.Label = global::Mono.Unix.Catalog.GetString("Use antivirus?");
			this.chkAntivirus.DrawIndicator = true;
			this.chkAntivirus.UseUnderline = true;
			this.vbox4.Add(this.chkAntivirus);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.chkAntivirus]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.frmClamd = new global::Gtk.Frame();
			this.frmClamd.Name = "frmClamd";
			this.frmClamd.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frmClamd.Gtk.Container+ContainerChild
			this.GtkAlignment6 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment6.Name = "GtkAlignment6";
			this.GtkAlignment6.LeftPadding = ((uint)(12));
			// Container child GtkAlignment6.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.chkClamd = new global::Gtk.CheckButton();
			this.chkClamd.CanFocus = true;
			this.chkClamd.Name = "chkClamd";
			this.chkClamd.Label = global::Mono.Unix.Catalog.GetString("Use clamd?");
			this.chkClamd.DrawIndicator = true;
			this.chkClamd.UseUnderline = true;
			this.vbox6.Add(this.chkClamd);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.chkClamd]));
			w28.Position = 0;
			w28.Expand = false;
			w28.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.lblClamdHost = new global::Gtk.Label();
			this.lblClamdHost.Name = "lblClamdHost";
			this.lblClamdHost.LabelProp = global::Mono.Unix.Catalog.GetString("Host");
			this.hbox3.Add(this.lblClamdHost);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.lblClamdHost]));
			w29.Position = 0;
			w29.Expand = false;
			w29.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.txtClamdHost = new global::Gtk.Entry();
			this.txtClamdHost.Sensitive = false;
			this.txtClamdHost.CanFocus = true;
			this.txtClamdHost.Name = "txtClamdHost";
			this.txtClamdHost.IsEditable = true;
			this.txtClamdHost.InvisibleChar = '●';
			this.hbox3.Add(this.txtClamdHost);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.txtClamdHost]));
			w30.Position = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.lblClamdPort = new global::Gtk.Label();
			this.lblClamdPort.Name = "lblClamdPort";
			this.lblClamdPort.LabelProp = global::Mono.Unix.Catalog.GetString("port");
			this.hbox3.Add(this.lblClamdPort);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.lblClamdPort]));
			w31.Position = 2;
			w31.Expand = false;
			w31.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.spClamdPort = new global::Gtk.SpinButton(1, 65535, 1);
			this.spClamdPort.Sensitive = false;
			this.spClamdPort.CanFocus = true;
			this.spClamdPort.Name = "spClamdPort";
			this.spClamdPort.Adjustment.PageIncrement = 10;
			this.spClamdPort.ClimbRate = 1;
			this.spClamdPort.Numeric = true;
			this.spClamdPort.Value = 3310;
			this.hbox3.Add(this.spClamdPort);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.spClamdPort]));
			w32.Position = 3;
			w32.Expand = false;
			w32.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.btnClamdTest = new global::Gtk.Button();
			this.btnClamdTest.Sensitive = false;
			this.btnClamdTest.CanFocus = true;
			this.btnClamdTest.Name = "btnClamdTest";
			this.btnClamdTest.UseUnderline = true;
			this.btnClamdTest.Label = global::Mono.Unix.Catalog.GetString("Test");
			this.hbox3.Add(this.btnClamdTest);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.btnClamdTest]));
			w33.Position = 4;
			w33.Expand = false;
			w33.Fill = false;
			this.vbox6.Add(this.hbox3);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox3]));
			w34.Position = 1;
			w34.Expand = false;
			w34.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.lblClamdVersion = new global::Gtk.Label();
			this.lblClamdVersion.Name = "lblClamdVersion";
			this.lblClamdVersion.LabelProp = global::Mono.Unix.Catalog.GetString("label4");
			this.vbox6.Add(this.lblClamdVersion);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.lblClamdVersion]));
			w35.Position = 2;
			w35.Expand = false;
			w35.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.chkClamdIsLocal = new global::Gtk.CheckButton();
			this.chkClamdIsLocal.Sensitive = false;
			this.chkClamdIsLocal.CanFocus = true;
			this.chkClamdIsLocal.Name = "chkClamdIsLocal";
			this.chkClamdIsLocal.Label = global::Mono.Unix.Catalog.GetString("Clamd is local?");
			this.chkClamdIsLocal.DrawIndicator = true;
			this.chkClamdIsLocal.UseUnderline = true;
			this.vbox6.Add(this.chkClamdIsLocal);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.chkClamdIsLocal]));
			w36.Position = 3;
			w36.Expand = false;
			w36.Fill = false;
			this.GtkAlignment6.Add(this.vbox6);
			this.frmClamd.Add(this.GtkAlignment6);
			this.GtkLabel8 = new global::Gtk.Label();
			this.GtkLabel8.Name = "GtkLabel8";
			this.GtkLabel8.LabelProp = global::Mono.Unix.Catalog.GetString("<b>clamd</b>");
			this.GtkLabel8.UseMarkup = true;
			this.frmClamd.LabelWidget = this.GtkLabel8;
			this.vbox4.Add(this.frmClamd);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.frmClamd]));
			w39.Position = 1;
			w39.Expand = false;
			w39.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.frmVirusTotal = new global::Gtk.Frame();
			this.frmVirusTotal.Name = "frmVirusTotal";
			this.frmVirusTotal.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frmVirusTotal.Gtk.Container+ContainerChild
			this.GtkAlignment7 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment7.Name = "GtkAlignment7";
			this.GtkAlignment7.LeftPadding = ((uint)(12));
			// Container child GtkAlignment7.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.chkVirusTotal = new global::Gtk.CheckButton();
			this.chkVirusTotal.CanFocus = true;
			this.chkVirusTotal.Name = "chkVirusTotal";
			this.chkVirusTotal.Label = global::Mono.Unix.Catalog.GetString("Use VirusTotal?");
			this.chkVirusTotal.DrawIndicator = true;
			this.chkVirusTotal.UseUnderline = true;
			this.vbox7.Add(this.chkVirusTotal);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.chkVirusTotal]));
			w40.Position = 0;
			w40.Expand = false;
			w40.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("API Key");
			this.hbox4.Add(this.label6);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label6]));
			w41.Position = 0;
			w41.Expand = false;
			w41.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.txtVirusTotal = new global::Gtk.Entry();
			this.txtVirusTotal.Sensitive = false;
			this.txtVirusTotal.CanFocus = true;
			this.txtVirusTotal.Name = "txtVirusTotal";
			this.txtVirusTotal.IsEditable = true;
			this.txtVirusTotal.InvisibleChar = '●';
			this.hbox4.Add(this.txtVirusTotal);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.txtVirusTotal]));
			w42.Position = 1;
			// Container child hbox4.Gtk.Box+BoxChild
			this.btnVirusTotal = new global::Gtk.Button();
			this.btnVirusTotal.Sensitive = false;
			this.btnVirusTotal.CanFocus = true;
			this.btnVirusTotal.Name = "btnVirusTotal";
			this.btnVirusTotal.UseUnderline = true;
			this.btnVirusTotal.Label = global::Mono.Unix.Catalog.GetString("Test");
			this.hbox4.Add(this.btnVirusTotal);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.btnVirusTotal]));
			w43.Position = 2;
			w43.Expand = false;
			w43.Fill = false;
			this.vbox7.Add(this.hbox4);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox4]));
			w44.Position = 1;
			w44.Expand = false;
			w44.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.lblVirusTotal = new global::Gtk.Label();
			this.lblVirusTotal.Name = "lblVirusTotal";
			this.lblVirusTotal.LabelProp = global::Mono.Unix.Catalog.GetString("label5");
			this.vbox7.Add(this.lblVirusTotal);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.lblVirusTotal]));
			w45.Position = 2;
			w45.Expand = false;
			w45.Fill = false;
			this.GtkAlignment7.Add(this.vbox7);
			this.frmVirusTotal.Add(this.GtkAlignment7);
			this.GtkLabel12 = new global::Gtk.Label();
			this.GtkLabel12.Name = "GtkLabel12";
			this.GtkLabel12.LabelProp = global::Mono.Unix.Catalog.GetString("<b>VirusTotal</b>");
			this.GtkLabel12.UseMarkup = true;
			this.frmVirusTotal.LabelWidget = this.GtkLabel12;
			this.vbox4.Add(this.frmVirusTotal);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.frmVirusTotal]));
			w48.Position = 2;
			w48.Expand = false;
			w48.Fill = false;
			this.hbox2.Add(this.vbox4);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox4]));
			w49.Position = 1;
			w49.Expand = false;
			w49.Fill = false;
			w1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(w1[this.hbox2]));
			w50.Position = 0;
			w50.Expand = false;
			w50.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox18 = new global::Gtk.HBox();
			this.hbox18.Name = "hbox18";
			this.hbox18.Spacing = 6;
			// Container child hbox18.Gtk.Box+BoxChild
			this.btnCancel = new global::Gtk.Button();
			this.btnCancel.CanFocus = true;
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.UseStock = true;
			this.btnCancel.UseUnderline = true;
			this.btnCancel.Label = "gtk-cancel";
			this.hbox18.Add(this.btnCancel);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.btnCancel]));
			w51.Position = 0;
			w51.Expand = false;
			w51.Fill = false;
			// Container child hbox18.Gtk.Box+BoxChild
			this.btnApply = new global::Gtk.Button();
			this.btnApply.CanFocus = true;
			this.btnApply.Name = "btnApply";
			this.btnApply.UseStock = true;
			this.btnApply.UseUnderline = true;
			this.btnApply.Label = "gtk-apply";
			this.hbox18.Add(this.btnApply);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.btnApply]));
			w52.PackType = ((global::Gtk.PackType)(1));
			w52.Position = 1;
			w52.Expand = false;
			w52.Fill = false;
			w1.Add(this.hbox18);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(w1[this.hbox18]));
			w53.Position = 1;
			w53.Expand = false;
			w53.Fill = false;
			// Internal child osrepodbmgr.dlgSettings.ActionArea
			global::Gtk.HButtonBox w54 = this.ActionArea;
			w54.Name = "__gtksharp_108_Stetic_TopLevelDialog_ActionArea";
			// Container child __gtksharp_108_Stetic_TopLevelDialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.btnDialog = new global::Gtk.Button();
			this.btnDialog.CanFocus = true;
			this.btnDialog.Name = "btnDialog";
			this.btnDialog.UseUnderline = true;
			this.btnDialog.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
			this.AddActionWidget(this.btnDialog, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w55 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w54[this.btnDialog]));
			w55.Expand = false;
			w55.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 680;
			this.DefaultHeight = 320;
			this.lblUnarVersion.Hide();
			this.lblVirusTotal.Hide();
			w54.Hide();
			this.Show();
			this.btnDatabase.Clicked += new global::System.EventHandler(this.OnBtnDatabaseClicked);
			this.btnRepository.Clicked += new global::System.EventHandler(this.OnBtnRepositoryClicked);
			this.btnTmp.Clicked += new global::System.EventHandler(this.OnBtnTmpClicked);
			this.btnUnar.Clicked += new global::System.EventHandler(this.OnBtnUnarClicked);
			this.chkAntivirus.Toggled += new global::System.EventHandler(this.OnChkAntivirusToggled);
			this.chkClamd.Toggled += new global::System.EventHandler(this.OnChkClamdToggled);
			this.btnClamdTest.Clicked += new global::System.EventHandler(this.OnBtnClamdTestClicked);
			this.chkVirusTotal.Toggled += new global::System.EventHandler(this.OnChkVirusTotalToggled);
			this.btnVirusTotal.Clicked += new global::System.EventHandler(this.OnBtnVirusTotalClicked);
			this.btnCancel.Clicked += new global::System.EventHandler(this.OnBtnCancelClicked);
			this.btnApply.Clicked += new global::System.EventHandler(this.OnBtnApplyClicked);
		}
	}
}
