
// This file has been generated by the GUI designer. Do not modify.
namespace osrepodbmgr
{
	public partial class dlgFilesystem
	{
		private global::Gtk.VBox vbox24;

		private global::Gtk.HBox hbox69;

		private global::Gtk.Label lblType;

		private global::Gtk.Entry txtType;

		private global::Gtk.HBox hbox86;

		private global::Gtk.Entry txtFiles;

		private global::Gtk.Label lblFiles;

		private global::Gtk.CheckButton chkBootable;

		private global::Gtk.CheckButton chkDirty;

		private global::Gtk.HBox hbox71;

		private global::Gtk.SpinButton spClusterSize;

		private global::Gtk.Label lblClusterSize;

		private global::Gtk.Entry txtClusters;

		private global::Gtk.Label lblClusters;

		private global::Gtk.Entry txtFreeClusters;

		private global::Gtk.Label lblFreeClusters;

		private global::Gtk.HBox hbox72;

		private global::Gtk.VBox vbox25;

		private global::Gtk.CheckButton chkCreationDate;

		private global::Gtk.Calendar cldCreationDate;

		private global::Gtk.VBox vbox28;

		private global::Gtk.CheckButton chkModificationDate;

		private global::Gtk.Calendar cldModificationDate;

		private global::Gtk.VBox vbox27;

		private global::Gtk.CheckButton chkEffectiveDate;

		private global::Gtk.Calendar cldEffectiveDate;

		private global::Gtk.VBox vbox26;

		private global::Gtk.CheckButton chkExpirationDate;

		private global::Gtk.Calendar cldExpirationDate;

		private global::Gtk.HPaned hpaned3;

		private global::Gtk.VBox vbox29;

		private global::Gtk.CheckButton chkBackupDate;

		private global::Gtk.Calendar cldBackupDate;

		private global::Gtk.VBox vbox31;

		private global::Gtk.HBox hbox85;

		private global::Gtk.Label lblLabel;

		private global::Gtk.Entry txtLabel;

		private global::Gtk.HBox hbox84;

		private global::Gtk.Label lblSerial;

		private global::Gtk.Entry txtSerial;

		private global::Gtk.Frame frame27;

		private global::Gtk.Alignment GtkAlignment2;

		private global::Gtk.VBox vbox32;

		private global::Gtk.HBox hbox87;

		private global::Gtk.Label lblSysId;

		private global::Gtk.Entry txtSysId;

		private global::Gtk.HBox hbox88;

		private global::Gtk.Label lblVolId;

		private global::Gtk.Entry txtVolId;

		private global::Gtk.HBox hbox89;

		private global::Gtk.Label lblPubId;

		private global::Gtk.Entry txtPubId;

		private global::Gtk.HBox hbox90;

		private global::Gtk.Label lblDataId;

		private global::Gtk.Entry txtDataId;

		private global::Gtk.HBox hbox91;

		private global::Gtk.Label lblAppId;

		private global::Gtk.Entry txtAppId;

		private global::Gtk.Label GtkLabel9;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Button btnSave;

		private global::Gtk.Button btnCancel;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget osrepodbmgr.dlgFilesystem
			this.Name = "osrepodbmgr.dlgFilesystem";
			this.Title = global::Mono.Unix.Catalog.GetString("Edit filesystem metadata");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child osrepodbmgr.dlgFilesystem.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox24 = new global::Gtk.VBox();
			this.vbox24.Name = "vbox24";
			this.vbox24.Spacing = 6;
			// Container child vbox24.Gtk.Box+BoxChild
			this.hbox69 = new global::Gtk.HBox();
			this.hbox69.Name = "hbox69";
			this.hbox69.Spacing = 6;
			// Container child hbox69.Gtk.Box+BoxChild
			this.lblType = new global::Gtk.Label();
			this.lblType.Name = "lblType";
			this.lblType.LabelProp = global::Mono.Unix.Catalog.GetString("Filesystem type");
			this.hbox69.Add(this.lblType);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox69[this.lblType]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox69.Gtk.Box+BoxChild
			this.txtType = new global::Gtk.Entry();
			this.txtType.CanFocus = true;
			this.txtType.Name = "txtType";
			this.txtType.IsEditable = true;
			this.txtType.InvisibleChar = '●';
			this.hbox69.Add(this.txtType);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox69[this.txtType]));
			w3.Position = 1;
			this.vbox24.Add(this.hbox69);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox24[this.hbox69]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox24.Gtk.Box+BoxChild
			this.hbox86 = new global::Gtk.HBox();
			this.hbox86.Name = "hbox86";
			this.hbox86.Spacing = 6;
			// Container child hbox86.Gtk.Box+BoxChild
			this.txtFiles = new global::Gtk.Entry();
			this.txtFiles.CanFocus = true;
			this.txtFiles.Name = "txtFiles";
			this.txtFiles.IsEditable = true;
			this.txtFiles.InvisibleChar = '●';
			this.hbox86.Add(this.txtFiles);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox86[this.txtFiles]));
			w5.Position = 0;
			// Container child hbox86.Gtk.Box+BoxChild
			this.lblFiles = new global::Gtk.Label();
			this.lblFiles.Name = "lblFiles";
			this.lblFiles.LabelProp = global::Mono.Unix.Catalog.GetString("files");
			this.hbox86.Add(this.lblFiles);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox86[this.lblFiles]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox86.Gtk.Box+BoxChild
			this.chkBootable = new global::Gtk.CheckButton();
			this.chkBootable.CanFocus = true;
			this.chkBootable.Name = "chkBootable";
			this.chkBootable.Label = global::Mono.Unix.Catalog.GetString("Bootable");
			this.chkBootable.DrawIndicator = true;
			this.chkBootable.UseUnderline = true;
			this.hbox86.Add(this.chkBootable);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox86[this.chkBootable]));
			w7.Position = 2;
			// Container child hbox86.Gtk.Box+BoxChild
			this.chkDirty = new global::Gtk.CheckButton();
			this.chkDirty.CanFocus = true;
			this.chkDirty.Name = "chkDirty";
			this.chkDirty.Label = global::Mono.Unix.Catalog.GetString("Dirty");
			this.chkDirty.DrawIndicator = true;
			this.chkDirty.UseUnderline = true;
			this.hbox86.Add(this.chkDirty);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox86[this.chkDirty]));
			w8.Position = 3;
			this.vbox24.Add(this.hbox86);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox24[this.hbox86]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox24.Gtk.Box+BoxChild
			this.hbox71 = new global::Gtk.HBox();
			this.hbox71.Name = "hbox71";
			this.hbox71.Spacing = 6;
			// Container child hbox71.Gtk.Box+BoxChild
			this.spClusterSize = new global::Gtk.SpinButton(0, 1048576, 1);
			this.spClusterSize.CanFocus = true;
			this.spClusterSize.Name = "spClusterSize";
			this.spClusterSize.Adjustment.PageIncrement = 10;
			this.spClusterSize.ClimbRate = 1;
			this.spClusterSize.Numeric = true;
			this.hbox71.Add(this.spClusterSize);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox71[this.spClusterSize]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox71.Gtk.Box+BoxChild
			this.lblClusterSize = new global::Gtk.Label();
			this.lblClusterSize.Name = "lblClusterSize";
			this.lblClusterSize.LabelProp = global::Mono.Unix.Catalog.GetString("bytes per cluster");
			this.hbox71.Add(this.lblClusterSize);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox71[this.lblClusterSize]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox71.Gtk.Box+BoxChild
			this.txtClusters = new global::Gtk.Entry();
			this.txtClusters.CanFocus = true;
			this.txtClusters.Name = "txtClusters";
			this.txtClusters.IsEditable = true;
			this.txtClusters.InvisibleChar = '●';
			this.hbox71.Add(this.txtClusters);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox71[this.txtClusters]));
			w12.Position = 2;
			// Container child hbox71.Gtk.Box+BoxChild
			this.lblClusters = new global::Gtk.Label();
			this.lblClusters.Name = "lblClusters";
			this.lblClusters.LabelProp = global::Mono.Unix.Catalog.GetString("clusters");
			this.hbox71.Add(this.lblClusters);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox71[this.lblClusters]));
			w13.Position = 3;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox71.Gtk.Box+BoxChild
			this.txtFreeClusters = new global::Gtk.Entry();
			this.txtFreeClusters.CanFocus = true;
			this.txtFreeClusters.Name = "txtFreeClusters";
			this.txtFreeClusters.IsEditable = true;
			this.txtFreeClusters.InvisibleChar = '●';
			this.hbox71.Add(this.txtFreeClusters);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox71[this.txtFreeClusters]));
			w14.Position = 4;
			// Container child hbox71.Gtk.Box+BoxChild
			this.lblFreeClusters = new global::Gtk.Label();
			this.lblFreeClusters.Name = "lblFreeClusters";
			this.lblFreeClusters.LabelProp = global::Mono.Unix.Catalog.GetString("free clusters");
			this.hbox71.Add(this.lblFreeClusters);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox71[this.lblFreeClusters]));
			w15.Position = 5;
			w15.Expand = false;
			w15.Fill = false;
			this.vbox24.Add(this.hbox71);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox24[this.hbox71]));
			w16.Position = 2;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox24.Gtk.Box+BoxChild
			this.hbox72 = new global::Gtk.HBox();
			this.hbox72.Name = "hbox72";
			this.hbox72.Spacing = 6;
			// Container child hbox72.Gtk.Box+BoxChild
			this.vbox25 = new global::Gtk.VBox();
			this.vbox25.Name = "vbox25";
			this.vbox25.Spacing = 6;
			// Container child vbox25.Gtk.Box+BoxChild
			this.chkCreationDate = new global::Gtk.CheckButton();
			this.chkCreationDate.CanFocus = true;
			this.chkCreationDate.Name = "chkCreationDate";
			this.chkCreationDate.Label = global::Mono.Unix.Catalog.GetString("Creation date");
			this.chkCreationDate.DrawIndicator = true;
			this.chkCreationDate.UseUnderline = true;
			this.vbox25.Add(this.chkCreationDate);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox25[this.chkCreationDate]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox25.Gtk.Box+BoxChild
			this.cldCreationDate = new global::Gtk.Calendar();
			this.cldCreationDate.Sensitive = false;
			this.cldCreationDate.CanFocus = true;
			this.cldCreationDate.Name = "cldCreationDate";
			this.cldCreationDate.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.vbox25.Add(this.cldCreationDate);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox25[this.cldCreationDate]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.hbox72.Add(this.vbox25);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox72[this.vbox25]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			// Container child hbox72.Gtk.Box+BoxChild
			this.vbox28 = new global::Gtk.VBox();
			this.vbox28.Name = "vbox28";
			this.vbox28.Spacing = 6;
			// Container child vbox28.Gtk.Box+BoxChild
			this.chkModificationDate = new global::Gtk.CheckButton();
			this.chkModificationDate.CanFocus = true;
			this.chkModificationDate.Name = "chkModificationDate";
			this.chkModificationDate.Label = global::Mono.Unix.Catalog.GetString("Modification date");
			this.chkModificationDate.DrawIndicator = true;
			this.chkModificationDate.UseUnderline = true;
			this.vbox28.Add(this.chkModificationDate);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox28[this.chkModificationDate]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox28.Gtk.Box+BoxChild
			this.cldModificationDate = new global::Gtk.Calendar();
			this.cldModificationDate.Sensitive = false;
			this.cldModificationDate.CanFocus = true;
			this.cldModificationDate.Name = "cldModificationDate";
			this.cldModificationDate.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.vbox28.Add(this.cldModificationDate);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox28[this.cldModificationDate]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			this.hbox72.Add(this.vbox28);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox72[this.vbox28]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox72.Gtk.Box+BoxChild
			this.vbox27 = new global::Gtk.VBox();
			this.vbox27.Name = "vbox27";
			this.vbox27.Spacing = 6;
			// Container child vbox27.Gtk.Box+BoxChild
			this.chkEffectiveDate = new global::Gtk.CheckButton();
			this.chkEffectiveDate.CanFocus = true;
			this.chkEffectiveDate.Name = "chkEffectiveDate";
			this.chkEffectiveDate.Label = global::Mono.Unix.Catalog.GetString("Effective date");
			this.chkEffectiveDate.DrawIndicator = true;
			this.chkEffectiveDate.UseUnderline = true;
			this.vbox27.Add(this.chkEffectiveDate);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox27[this.chkEffectiveDate]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox27.Gtk.Box+BoxChild
			this.cldEffectiveDate = new global::Gtk.Calendar();
			this.cldEffectiveDate.Sensitive = false;
			this.cldEffectiveDate.CanFocus = true;
			this.cldEffectiveDate.Name = "cldEffectiveDate";
			this.cldEffectiveDate.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.vbox27.Add(this.cldEffectiveDate);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox27[this.cldEffectiveDate]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			this.hbox72.Add(this.vbox27);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox72[this.vbox27]));
			w25.Position = 2;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox72.Gtk.Box+BoxChild
			this.vbox26 = new global::Gtk.VBox();
			this.vbox26.Name = "vbox26";
			this.vbox26.Spacing = 6;
			// Container child vbox26.Gtk.Box+BoxChild
			this.chkExpirationDate = new global::Gtk.CheckButton();
			this.chkExpirationDate.CanFocus = true;
			this.chkExpirationDate.Name = "chkExpirationDate";
			this.chkExpirationDate.Label = global::Mono.Unix.Catalog.GetString("Expiration date");
			this.chkExpirationDate.DrawIndicator = true;
			this.chkExpirationDate.UseUnderline = true;
			this.vbox26.Add(this.chkExpirationDate);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox26[this.chkExpirationDate]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox26.Gtk.Box+BoxChild
			this.cldExpirationDate = new global::Gtk.Calendar();
			this.cldExpirationDate.Sensitive = false;
			this.cldExpirationDate.CanFocus = true;
			this.cldExpirationDate.Name = "cldExpirationDate";
			this.cldExpirationDate.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.vbox26.Add(this.cldExpirationDate);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox26[this.cldExpirationDate]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			this.hbox72.Add(this.vbox26);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox72[this.vbox26]));
			w28.Position = 3;
			w28.Expand = false;
			w28.Fill = false;
			this.vbox24.Add(this.hbox72);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox24[this.hbox72]));
			w29.Position = 3;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox24.Gtk.Box+BoxChild
			this.hpaned3 = new global::Gtk.HPaned();
			this.hpaned3.CanFocus = true;
			this.hpaned3.Name = "hpaned3";
			this.hpaned3.Position = 220;
			// Container child hpaned3.Gtk.Paned+PanedChild
			this.vbox29 = new global::Gtk.VBox();
			this.vbox29.Name = "vbox29";
			this.vbox29.Spacing = 6;
			// Container child vbox29.Gtk.Box+BoxChild
			this.chkBackupDate = new global::Gtk.CheckButton();
			this.chkBackupDate.CanFocus = true;
			this.chkBackupDate.Name = "chkBackupDate";
			this.chkBackupDate.Label = global::Mono.Unix.Catalog.GetString("Last backup date");
			this.chkBackupDate.DrawIndicator = true;
			this.chkBackupDate.UseUnderline = true;
			this.vbox29.Add(this.chkBackupDate);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox29[this.chkBackupDate]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			// Container child vbox29.Gtk.Box+BoxChild
			this.cldBackupDate = new global::Gtk.Calendar();
			this.cldBackupDate.Sensitive = false;
			this.cldBackupDate.CanFocus = true;
			this.cldBackupDate.Name = "cldBackupDate";
			this.cldBackupDate.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.vbox29.Add(this.cldBackupDate);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox29[this.cldBackupDate]));
			w31.Position = 1;
			w31.Expand = false;
			w31.Fill = false;
			this.hpaned3.Add(this.vbox29);
			global::Gtk.Paned.PanedChild w32 = ((global::Gtk.Paned.PanedChild)(this.hpaned3[this.vbox29]));
			w32.Resize = false;
			// Container child hpaned3.Gtk.Paned+PanedChild
			this.vbox31 = new global::Gtk.VBox();
			this.vbox31.Name = "vbox31";
			this.vbox31.Spacing = 6;
			// Container child vbox31.Gtk.Box+BoxChild
			this.hbox85 = new global::Gtk.HBox();
			this.hbox85.Name = "hbox85";
			this.hbox85.Spacing = 6;
			// Container child hbox85.Gtk.Box+BoxChild
			this.lblLabel = new global::Gtk.Label();
			this.lblLabel.Name = "lblLabel";
			this.lblLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Volume label");
			this.hbox85.Add(this.lblLabel);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox85[this.lblLabel]));
			w33.Position = 0;
			w33.Expand = false;
			w33.Fill = false;
			// Container child hbox85.Gtk.Box+BoxChild
			this.txtLabel = new global::Gtk.Entry();
			this.txtLabel.CanFocus = true;
			this.txtLabel.Name = "txtLabel";
			this.txtLabel.IsEditable = true;
			this.txtLabel.InvisibleChar = '●';
			this.hbox85.Add(this.txtLabel);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox85[this.txtLabel]));
			w34.Position = 1;
			this.vbox31.Add(this.hbox85);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox31[this.hbox85]));
			w35.Position = 0;
			w35.Expand = false;
			w35.Fill = false;
			// Container child vbox31.Gtk.Box+BoxChild
			this.hbox84 = new global::Gtk.HBox();
			this.hbox84.Name = "hbox84";
			this.hbox84.Spacing = 6;
			// Container child hbox84.Gtk.Box+BoxChild
			this.lblSerial = new global::Gtk.Label();
			this.lblSerial.Name = "lblSerial";
			this.lblSerial.LabelProp = global::Mono.Unix.Catalog.GetString("Volume serial");
			this.hbox84.Add(this.lblSerial);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox84[this.lblSerial]));
			w36.Position = 0;
			w36.Expand = false;
			w36.Fill = false;
			// Container child hbox84.Gtk.Box+BoxChild
			this.txtSerial = new global::Gtk.Entry();
			this.txtSerial.CanFocus = true;
			this.txtSerial.Name = "txtSerial";
			this.txtSerial.IsEditable = true;
			this.txtSerial.InvisibleChar = '●';
			this.hbox84.Add(this.txtSerial);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox84[this.txtSerial]));
			w37.Position = 1;
			this.vbox31.Add(this.hbox84);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox31[this.hbox84]));
			w38.Position = 1;
			w38.Expand = false;
			w38.Fill = false;
			// Container child vbox31.Gtk.Box+BoxChild
			this.frame27 = new global::Gtk.Frame();
			this.frame27.Name = "frame27";
			this.frame27.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame27.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.vbox32 = new global::Gtk.VBox();
			this.vbox32.Name = "vbox32";
			this.vbox32.Spacing = 6;
			// Container child vbox32.Gtk.Box+BoxChild
			this.hbox87 = new global::Gtk.HBox();
			this.hbox87.Name = "hbox87";
			this.hbox87.Spacing = 6;
			// Container child hbox87.Gtk.Box+BoxChild
			this.lblSysId = new global::Gtk.Label();
			this.lblSysId.Name = "lblSysId";
			this.lblSysId.LabelProp = global::Mono.Unix.Catalog.GetString("System identifier");
			this.hbox87.Add(this.lblSysId);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox87[this.lblSysId]));
			w39.Position = 0;
			w39.Expand = false;
			w39.Fill = false;
			// Container child hbox87.Gtk.Box+BoxChild
			this.txtSysId = new global::Gtk.Entry();
			this.txtSysId.CanFocus = true;
			this.txtSysId.Name = "txtSysId";
			this.txtSysId.IsEditable = true;
			this.txtSysId.InvisibleChar = '●';
			this.hbox87.Add(this.txtSysId);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox87[this.txtSysId]));
			w40.Position = 1;
			this.vbox32.Add(this.hbox87);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox32[this.hbox87]));
			w41.Position = 0;
			w41.Expand = false;
			w41.Fill = false;
			// Container child vbox32.Gtk.Box+BoxChild
			this.hbox88 = new global::Gtk.HBox();
			this.hbox88.Name = "hbox88";
			this.hbox88.Spacing = 6;
			// Container child hbox88.Gtk.Box+BoxChild
			this.lblVolId = new global::Gtk.Label();
			this.lblVolId.Name = "lblVolId";
			this.lblVolId.LabelProp = global::Mono.Unix.Catalog.GetString("Volume identifier");
			this.hbox88.Add(this.lblVolId);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox88[this.lblVolId]));
			w42.Position = 0;
			w42.Expand = false;
			w42.Fill = false;
			// Container child hbox88.Gtk.Box+BoxChild
			this.txtVolId = new global::Gtk.Entry();
			this.txtVolId.CanFocus = true;
			this.txtVolId.Name = "txtVolId";
			this.txtVolId.IsEditable = true;
			this.txtVolId.InvisibleChar = '●';
			this.hbox88.Add(this.txtVolId);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox88[this.txtVolId]));
			w43.Position = 1;
			this.vbox32.Add(this.hbox88);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox32[this.hbox88]));
			w44.Position = 1;
			w44.Expand = false;
			w44.Fill = false;
			// Container child vbox32.Gtk.Box+BoxChild
			this.hbox89 = new global::Gtk.HBox();
			this.hbox89.Name = "hbox89";
			this.hbox89.Spacing = 6;
			// Container child hbox89.Gtk.Box+BoxChild
			this.lblPubId = new global::Gtk.Label();
			this.lblPubId.Name = "lblPubId";
			this.lblPubId.LabelProp = global::Mono.Unix.Catalog.GetString("Publisher identifier");
			this.hbox89.Add(this.lblPubId);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox89[this.lblPubId]));
			w45.Position = 0;
			w45.Expand = false;
			w45.Fill = false;
			// Container child hbox89.Gtk.Box+BoxChild
			this.txtPubId = new global::Gtk.Entry();
			this.txtPubId.CanFocus = true;
			this.txtPubId.Name = "txtPubId";
			this.txtPubId.IsEditable = true;
			this.txtPubId.InvisibleChar = '●';
			this.hbox89.Add(this.txtPubId);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox89[this.txtPubId]));
			w46.Position = 1;
			this.vbox32.Add(this.hbox89);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox32[this.hbox89]));
			w47.Position = 2;
			w47.Expand = false;
			w47.Fill = false;
			// Container child vbox32.Gtk.Box+BoxChild
			this.hbox90 = new global::Gtk.HBox();
			this.hbox90.Name = "hbox90";
			this.hbox90.Spacing = 6;
			// Container child hbox90.Gtk.Box+BoxChild
			this.lblDataId = new global::Gtk.Label();
			this.lblDataId.Name = "lblDataId";
			this.lblDataId.LabelProp = global::Mono.Unix.Catalog.GetString("Data preparer identifier");
			this.hbox90.Add(this.lblDataId);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox90[this.lblDataId]));
			w48.Position = 0;
			w48.Expand = false;
			w48.Fill = false;
			// Container child hbox90.Gtk.Box+BoxChild
			this.txtDataId = new global::Gtk.Entry();
			this.txtDataId.CanFocus = true;
			this.txtDataId.Name = "txtDataId";
			this.txtDataId.IsEditable = true;
			this.txtDataId.InvisibleChar = '●';
			this.hbox90.Add(this.txtDataId);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox90[this.txtDataId]));
			w49.Position = 1;
			this.vbox32.Add(this.hbox90);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vbox32[this.hbox90]));
			w50.Position = 3;
			w50.Expand = false;
			w50.Fill = false;
			// Container child vbox32.Gtk.Box+BoxChild
			this.hbox91 = new global::Gtk.HBox();
			this.hbox91.Name = "hbox91";
			this.hbox91.Spacing = 6;
			// Container child hbox91.Gtk.Box+BoxChild
			this.lblAppId = new global::Gtk.Label();
			this.lblAppId.Name = "lblAppId";
			this.lblAppId.LabelProp = global::Mono.Unix.Catalog.GetString("Application identifier");
			this.hbox91.Add(this.lblAppId);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox91[this.lblAppId]));
			w51.Position = 0;
			w51.Expand = false;
			w51.Fill = false;
			// Container child hbox91.Gtk.Box+BoxChild
			this.txtAppId = new global::Gtk.Entry();
			this.txtAppId.CanFocus = true;
			this.txtAppId.Name = "txtAppId";
			this.txtAppId.IsEditable = true;
			this.txtAppId.InvisibleChar = '●';
			this.hbox91.Add(this.txtAppId);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox91[this.txtAppId]));
			w52.Position = 1;
			this.vbox32.Add(this.hbox91);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vbox32[this.hbox91]));
			w53.Position = 4;
			w53.Expand = false;
			w53.Fill = false;
			this.GtkAlignment2.Add(this.vbox32);
			this.frame27.Add(this.GtkAlignment2);
			this.GtkLabel9 = new global::Gtk.Label();
			this.GtkLabel9.Name = "GtkLabel9";
			this.GtkLabel9.LabelProp = global::Mono.Unix.Catalog.GetString("<b>ISO9660 information</b>");
			this.GtkLabel9.UseMarkup = true;
			this.frame27.LabelWidget = this.GtkLabel9;
			this.vbox31.Add(this.frame27);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.vbox31[this.frame27]));
			w56.Position = 2;
			w56.Expand = false;
			w56.Fill = false;
			this.hpaned3.Add(this.vbox31);
			this.vbox24.Add(this.hpaned3);
			global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.vbox24[this.hpaned3]));
			w58.Position = 4;
			w58.Expand = false;
			w58.Fill = false;
			w1.Add(this.vbox24);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(w1[this.vbox24]));
			w59.Position = 0;
			w59.Expand = false;
			w59.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnSave = new global::Gtk.Button();
			this.btnSave.CanFocus = true;
			this.btnSave.Name = "btnSave";
			this.btnSave.UseStock = true;
			this.btnSave.UseUnderline = true;
			this.btnSave.Label = "gtk-save";
			this.hbox2.Add(this.btnSave);
			global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnSave]));
			w60.PackType = ((global::Gtk.PackType)(1));
			w60.Position = 0;
			w60.Expand = false;
			w60.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnCancel = new global::Gtk.Button();
			this.btnCancel.CanFocus = true;
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.UseStock = true;
			this.btnCancel.UseUnderline = true;
			this.btnCancel.Label = "gtk-cancel";
			this.hbox2.Add(this.btnCancel);
			global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnCancel]));
			w61.PackType = ((global::Gtk.PackType)(1));
			w61.Position = 1;
			w61.Expand = false;
			w61.Fill = false;
			w1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(w1[this.hbox2]));
			w62.PackType = ((global::Gtk.PackType)(1));
			w62.Position = 2;
			w62.Expand = false;
			w62.Fill = false;
			// Internal child osrepodbmgr.dlgFilesystem.ActionArea
			global::Gtk.HButtonBox w63 = this.ActionArea;
			w63.Name = "dialog1_ActionArea";
			w63.Spacing = 10;
			w63.BorderWidth = ((uint)(5));
			w63.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget(this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w64 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w63[this.buttonCancel]));
			w64.Expand = false;
			w64.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w65 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w63[this.buttonOk]));
			w65.Position = 1;
			w65.Expand = false;
			w65.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 902;
			this.DefaultHeight = 594;
			w63.Hide();
			this.Show();
			this.chkCreationDate.Toggled += new global::System.EventHandler(this.OnChkCreationDateToggled);
			this.chkModificationDate.Toggled += new global::System.EventHandler(this.OnChkModificationDateToggled);
			this.chkEffectiveDate.Toggled += new global::System.EventHandler(this.OnChkEffectiveDateToggled);
			this.chkExpirationDate.Toggled += new global::System.EventHandler(this.OnChkExpirationDateToggled);
			this.chkBackupDate.Toggled += new global::System.EventHandler(this.OnChkBackupDateToggled);
			this.btnCancel.Clicked += new global::System.EventHandler(this.OnBtnCancelClicked);
			this.btnSave.Clicked += new global::System.EventHandler(this.OnBtnSaveClicked);
			this.buttonOk.Clicked += new global::System.EventHandler(this.OnButtonOkClicked);
		}
	}
}
