
// This file has been generated by the GUI designer. Do not modify.
namespace osrepodbmgr
{
	public partial class frmSettings
	{
		private global::Gtk.VBox vbox5;

		private global::Gtk.HBox hbox26;

		private global::Gtk.Label lblDatabase;

		private global::Gtk.Entry txtDatabase;

		private global::Gtk.Button btnDatabase;

		private global::Gtk.HBox hbox25;

		private global::Gtk.Label lblRepository;

		private global::Gtk.Entry txtRepository;

		private global::Gtk.Button btnRepository;

		private global::Gtk.HBox hbox24;

		private global::Gtk.Label lblTmp;

		private global::Gtk.Entry txtTmp;

		private global::Gtk.Button btnTmp;

		private global::Gtk.HBox hbox23;

		private global::Gtk.Label lblUnar;

		private global::Gtk.Entry txtUnar;

		private global::Gtk.Button btnUnar;

		private global::Gtk.Label lblUnarVersion;

		private global::Gtk.HBox hbox18;

		private global::Gtk.Button btnCancel;

		private global::Gtk.Button btnApply;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget osrepodbmgr.frmSettings
			this.Name = "osrepodbmgr.frmSettings";
			this.Title = global::Mono.Unix.Catalog.GetString("frmSettings");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child osrepodbmgr.frmSettings.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox26 = new global::Gtk.HBox();
			this.hbox26.Name = "hbox26";
			this.hbox26.Spacing = 6;
			// Container child hbox26.Gtk.Box+BoxChild
			this.lblDatabase = new global::Gtk.Label();
			this.lblDatabase.Name = "lblDatabase";
			this.lblDatabase.LabelProp = global::Mono.Unix.Catalog.GetString("Database file");
			this.hbox26.Add(this.lblDatabase);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.lblDatabase]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox26.Gtk.Box+BoxChild
			this.txtDatabase = new global::Gtk.Entry();
			this.txtDatabase.CanFocus = true;
			this.txtDatabase.Name = "txtDatabase";
			this.txtDatabase.IsEditable = true;
			this.txtDatabase.InvisibleChar = '●';
			this.hbox26.Add(this.txtDatabase);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.txtDatabase]));
			w2.Position = 1;
			// Container child hbox26.Gtk.Box+BoxChild
			this.btnDatabase = new global::Gtk.Button();
			this.btnDatabase.CanFocus = true;
			this.btnDatabase.Name = "btnDatabase";
			this.btnDatabase.UseUnderline = true;
			this.btnDatabase.Label = global::Mono.Unix.Catalog.GetString("Choose");
			global::Gtk.Image w3 = new global::Gtk.Image();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-open", global::Gtk.IconSize.Menu);
			this.btnDatabase.Image = w3;
			this.hbox26.Add(this.btnDatabase);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.btnDatabase]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox5.Add(this.hbox26);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox26]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox25 = new global::Gtk.HBox();
			this.hbox25.Name = "hbox25";
			this.hbox25.Spacing = 6;
			// Container child hbox25.Gtk.Box+BoxChild
			this.lblRepository = new global::Gtk.Label();
			this.lblRepository.Name = "lblRepository";
			this.lblRepository.LabelProp = global::Mono.Unix.Catalog.GetString("Repository folder");
			this.hbox25.Add(this.lblRepository);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.lblRepository]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox25.Gtk.Box+BoxChild
			this.txtRepository = new global::Gtk.Entry();
			this.txtRepository.CanFocus = true;
			this.txtRepository.Name = "txtRepository";
			this.txtRepository.IsEditable = true;
			this.txtRepository.InvisibleChar = '●';
			this.hbox25.Add(this.txtRepository);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.txtRepository]));
			w7.Position = 1;
			// Container child hbox25.Gtk.Box+BoxChild
			this.btnRepository = new global::Gtk.Button();
			this.btnRepository.CanFocus = true;
			this.btnRepository.Name = "btnRepository";
			this.btnRepository.UseUnderline = true;
			this.btnRepository.Label = global::Mono.Unix.Catalog.GetString("Choose");
			global::Gtk.Image w8 = new global::Gtk.Image();
			w8.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-open", global::Gtk.IconSize.Menu);
			this.btnRepository.Image = w8;
			this.hbox25.Add(this.btnRepository);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.btnRepository]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.vbox5.Add(this.hbox25);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox25]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox24 = new global::Gtk.HBox();
			this.hbox24.Name = "hbox24";
			this.hbox24.Spacing = 6;
			// Container child hbox24.Gtk.Box+BoxChild
			this.lblTmp = new global::Gtk.Label();
			this.lblTmp.Name = "lblTmp";
			this.lblTmp.LabelProp = global::Mono.Unix.Catalog.GetString("Temporary folder");
			this.hbox24.Add(this.lblTmp);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.lblTmp]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox24.Gtk.Box+BoxChild
			this.txtTmp = new global::Gtk.Entry();
			this.txtTmp.CanFocus = true;
			this.txtTmp.Name = "txtTmp";
			this.txtTmp.IsEditable = true;
			this.txtTmp.InvisibleChar = '●';
			this.hbox24.Add(this.txtTmp);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.txtTmp]));
			w12.Position = 1;
			// Container child hbox24.Gtk.Box+BoxChild
			this.btnTmp = new global::Gtk.Button();
			this.btnTmp.CanFocus = true;
			this.btnTmp.Name = "btnTmp";
			this.btnTmp.UseUnderline = true;
			this.btnTmp.Label = global::Mono.Unix.Catalog.GetString("Choose");
			global::Gtk.Image w13 = new global::Gtk.Image();
			w13.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-open", global::Gtk.IconSize.Menu);
			this.btnTmp.Image = w13;
			this.hbox24.Add(this.btnTmp);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.btnTmp]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			this.vbox5.Add(this.hbox24);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox24]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox23 = new global::Gtk.HBox();
			this.hbox23.Name = "hbox23";
			this.hbox23.Spacing = 6;
			// Container child hbox23.Gtk.Box+BoxChild
			this.lblUnar = new global::Gtk.Label();
			this.lblUnar.Name = "lblUnar";
			this.lblUnar.LabelProp = global::Mono.Unix.Catalog.GetString("Path to unar");
			this.hbox23.Add(this.lblUnar);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.lblUnar]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox23.Gtk.Box+BoxChild
			this.txtUnar = new global::Gtk.Entry();
			this.txtUnar.CanFocus = true;
			this.txtUnar.Name = "txtUnar";
			this.txtUnar.IsEditable = true;
			this.txtUnar.InvisibleChar = '●';
			this.hbox23.Add(this.txtUnar);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.txtUnar]));
			w17.Position = 1;
			// Container child hbox23.Gtk.Box+BoxChild
			this.btnUnar = new global::Gtk.Button();
			this.btnUnar.CanFocus = true;
			this.btnUnar.Name = "btnUnar";
			this.btnUnar.UseUnderline = true;
			this.btnUnar.Label = global::Mono.Unix.Catalog.GetString("Choose");
			global::Gtk.Image w18 = new global::Gtk.Image();
			w18.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-open", global::Gtk.IconSize.Menu);
			this.btnUnar.Image = w18;
			this.hbox23.Add(this.btnUnar);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.btnUnar]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			this.vbox5.Add(this.hbox23);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox23]));
			w20.Position = 3;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.lblUnarVersion = new global::Gtk.Label();
			this.lblUnarVersion.Name = "lblUnarVersion";
			this.lblUnarVersion.LabelProp = global::Mono.Unix.Catalog.GetString("label1");
			this.vbox5.Add(this.lblUnarVersion);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.lblUnarVersion]));
			w21.Position = 4;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox18 = new global::Gtk.HBox();
			this.hbox18.Name = "hbox18";
			this.hbox18.Spacing = 6;
			// Container child hbox18.Gtk.Box+BoxChild
			this.btnCancel = new global::Gtk.Button();
			this.btnCancel.CanFocus = true;
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.UseStock = true;
			this.btnCancel.UseUnderline = true;
			this.btnCancel.Label = "gtk-cancel";
			this.hbox18.Add(this.btnCancel);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.btnCancel]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox18.Gtk.Box+BoxChild
			this.btnApply = new global::Gtk.Button();
			this.btnApply.CanFocus = true;
			this.btnApply.Name = "btnApply";
			this.btnApply.UseStock = true;
			this.btnApply.UseUnderline = true;
			this.btnApply.Label = "gtk-apply";
			this.hbox18.Add(this.btnApply);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.btnApply]));
			w23.PackType = ((global::Gtk.PackType)(1));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			this.vbox5.Add(this.hbox18);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox18]));
			w24.Position = 5;
			w24.Expand = false;
			w24.Fill = false;
			this.Add(this.vbox5);
			if((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 210;
			this.lblUnarVersion.Hide();
			this.Show();
			this.btnDatabase.Clicked += new global::System.EventHandler(this.OnBtnDatabaseClicked);
			this.btnRepository.Clicked += new global::System.EventHandler(this.OnBtnRepositoryClicked);
			this.btnTmp.Clicked += new global::System.EventHandler(this.OnBtnTmpClicked);
			this.btnUnar.Clicked += new global::System.EventHandler(this.OnBtnUnarClicked);
			this.btnCancel.Clicked += new global::System.EventHandler(this.OnBtnCancelClicked);
			this.btnApply.Clicked += new global::System.EventHandler(this.OnBtnApplyClicked);
		}
	}
}
